---
name: Build Pre-commit Container

on:
  # Primarily manual builds for cost control
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild even if no changes detected'
        required: false
        default: false
        type: boolean

  # Auto-build only when Dockerfile changes (critical)
  push:
    branches: [main]
    paths:
      - 'infra/docker/Dockerfile.precommit'
      - '.github/workflows/build-precommit-image.yml'

  # Optional: Auto-build when deps change (comment out to disable)
  # push:
  #   branches: [main]
  #   paths:
  #     - 'scripts/python/requirements-dev.txt'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and push pre-commit image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/precommit
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile.precommit
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: ${{ inputs.force_rebuild != true && 'type=gha' || '' }}
          cache-to: ${{ inputs.force_rebuild != true && 'type=gha,mode=max' || '' }}
          no-cache: ${{ inputs.force_rebuild == true }}
          platforms: linux/amd64
