name: Project v2 Status Sync

on:
  issues:
    types: [opened, closed, reopened, assigned, unassigned]
  pull_request:
    types: [opened, closed, ready_for_review, converted_to_draft]

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  sync-project-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install -r scripts/python/requirements.txt

      - name: Update Project Status (Issues)
        if: github.event_name == 'issues'
        env:
          GITHUB_TOKEN: ${{ secrets.USE_PROJECT_V2_TOKEN }}
        run: |
          python scripts/python/update_project_status.py \
            --event-name issues \
            --action "${{ github.event.action }}" \
            --issue-number "${{ github.event.issue.number }}" \
            --assignees ${{ join(github.event.issue.assignees.*.login, ' ') }}

      - name: Update Project Status (Pull Requests)
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.USE_PROJECT_V2_TOKEN }}
        run: |
          python scripts/python/update_project_status.py \
            --event-name pull_request \
            --action "${{ github.event.action }}" \
            --pr-number "${{ github.event.pull_request.number }}" \
            --pr-title "${{ github.event.pull_request.title }}" \
            --pr-body "${{ github.event.pull_request.body }}" \
            ${{ github.event.pull_request.draft && '--is-draft' || '' }} \
            ${{ github.event.pull_request.merged && '--is-merged' || '' }}
